#! /bin/bash

declare -A points=
(( p = 1 ))
for c in {a..z}; do points[$c]=$(( p++ )); done
for c in {A..Z}; do points[$c]=$(( p++ )); done

function f() {
  (
    local text=$1
    local l=$(( ${#text} - 1 ))
    for i in $(seq 0 ${l}); do
      echo ${text:i:1}
    done
  ) | sort | uniq
}

(( total  = 0 ))
while read; do
    #echo reply ${REPLY}
    (( length = ${#REPLY}, half = length / 2 ))
    t1=${REPLY:0:${half}}
    t2=${REPLY:${half}}
    #echo length ${length} ${half}
    #echo 1: ${t1}
    #echo 2: ${t2}
    r=$(
      (
        f ${t1}
        f ${t2}
      ) | sort | uniq -d
    )
    (( total += ${points[$r]} ))
    echo $r ${points[$r]} ${total}
    #echo
    #echo
done
